# Generated by Django 5.1.7 on 2026-07-16 02:50

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(db_index=True, max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_schemas_found', models.IntegerField(default=0)),
                ('total_errors', models.IntegerField(default=0)),
                ('total_warnings', models.IntegerField(default=0)),
                ('has_json_ld', models.BooleanField(default=False)),
                ('has_microdata', models.BooleanField(default=False)),
                ('has_rdfa', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'validation job',
                'verbose_name_plural': 'validation jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchemaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('schema_type', models.CharField(db_index=True, max_length=100)),
                ('format', models.CharField(choices=[('json-ld', 'JSON-LD'), ('microdata', 'Microdata'), ('rdfa', 'RDFa')], db_index=True, max_length=10)),
                ('raw_data', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(db_index=True, default=False)),
                ('google_rich_result_eligible', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='validator.validationjob')),
            ],
            options={
                'verbose_name': 'schema item',
                'verbose_name_plural': 'schema items',
                'ordering': ['schema_type'],
            },
        ),
        migrations.CreateModel(
            name='SchemaIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], db_index=True, max_length=10)),
                ('field', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('schema_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='validator.schemaitem')),
            ],
            options={
                'verbose_name': 'schema issue',
                'verbose_name_plural': 'schema issues',
                'ordering': ['severity', 'field'],
                'indexes': [models.Index(fields=['schema_item', 'severity'], name='issue_item_sev_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='validationjob',
            index=models.Index(fields=['user', '-created_at'], name='val_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='validationjob',
            index=models.Index(fields=['status', '-created_at'], name='val_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='schemaitem',
            index=models.Index(fields=['job', 'schema_type'], name='schema_job_type_idx'),
        ),
        migrations.AddIndex(
            model_name='schemaitem',
            index=models.Index(fields=['job', 'format'], name='schema_job_format_idx'),
        ),
    ]
