# Generated by Django 5.1.7 on 2026-07-07 01:40

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessibilityAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(db_index=True, max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('total_errors', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('total_features', models.IntegerField(default=0)),
                ('total_structural', models.IntegerField(default=0)),
                ('total_contrast_errors', models.IntegerField(default=0)),
                ('wcag_level', models.CharField(blank=True, help_text='Estimated WCAG conformance: A / AA / AAA, or null if it fails.', max_length=3, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('credits_consumed', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accessibility audit',
                'verbose_name_plural': 'accessibility audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('issue_type', models.CharField(choices=[('error', 'Error'), ('alert', 'Alert'), ('feature', 'Feature'), ('structural', 'Structural'), ('contrast', 'Contrast')], db_index=True, max_length=12)),
                ('wave_id', models.CharField(help_text="WAVE item id, e.g. 'alt_missing'.", max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('count', models.IntegerField(default=0)),
                ('wcag_reference', models.CharField(blank=True, help_text="Related WCAG success criterion, e.g. '1.1.1'.", max_length=20, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='audits.accessibilityaudit')),
            ],
            options={
                'verbose_name': 'audit issue',
                'verbose_name_plural': 'audit issues',
                'ordering': ['issue_type', '-count'],
            },
        ),
        migrations.AddIndex(
            model_name='accessibilityaudit',
            index=models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityaudit',
            index=models.Index(fields=['url'], name='audit_url_idx'),
        ),
        migrations.AddIndex(
            model_name='accessibilityaudit',
            index=models.Index(fields=['status'], name='audit_status_idx'),
        ),
        migrations.AddIndex(
            model_name='auditissue',
            index=models.Index(fields=['audit', 'issue_type'], name='issue_audit_type_idx'),
        ),
    ]
