# Generated by Django 5.1.7 on 2026-07-07 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessibilityaudit',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for anonymous audits (no credit charged).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_audits', to=settings.AUTH_USER_MODEL),
        ),
    ]
