# Generated by Django 5.1.7 on 2026-07-08 07:51

import apps.common.validators
import apps.full_report.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FullReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('strategy', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], default='mobile', max_length=10)),
                ('lang', models.CharField(default='en', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.full_report.models.report_upload_to)),
                ('tools_status', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'full report',
                'verbose_name_plural': 'full reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fullreport_user_created_idx'), models.Index(fields=['status'], name='fullreport_status_idx')],
            },
        ),
    ]
