# Generated by Django 5.1.7 on 2026-06-30 23:33

import apps.common.validators
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('reports_count', models.IntegerField(default=0)),
                ('last_analyzed_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'analysis history',
                'verbose_name_plural': 'analysis history',
                'ordering': ['-last_analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(db_index=True, max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('strategy', models.CharField(choices=[('mobile', 'Mobile'), ('desktop', 'Desktop')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('performance_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accessibility_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('best_practices_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('seo_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('first_contentful_paint', models.FloatField(blank=True, help_text='seconds', null=True)),
                ('largest_contentful_paint', models.FloatField(blank=True, help_text='seconds', null=True)),
                ('total_blocking_time', models.FloatField(blank=True, help_text='milliseconds', null=True)),
                ('cumulative_layout_shift', models.FloatField(blank=True, help_text='unitless', null=True)),
                ('speed_index', models.FloatField(blank=True, help_text='seconds', null=True)),
                ('time_to_interactive', models.FloatField(blank=True, help_text='seconds', null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'analysis report',
                'verbose_name_plural': 'analysis reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
