# Generated by Django 5.1.7 on 2026-06-30 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='analysishistory',
            index=models.Index(fields=['user', '-last_analyzed_at'], name='history_user_last_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysishistory',
            constraint=models.UniqueConstraint(fields=('user', 'url'), name='unique_user_url_history'),
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['user', '-created_at'], name='report_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['url', 'strategy'], name='report_url_strategy_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisreport',
            index=models.Index(fields=['status'], name='report_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='analysisreport',
            constraint=models.CheckConstraint(condition=models.Q(('performance_score__isnull', True), models.Q(('performance_score__gte', 0), ('performance_score__lte', 100)), _connector='OR'), name='report_performance_score_range'),
        ),
    ]
