# Generated by Django 5.1.7 on 2026-07-04 02:35

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GTmetrixReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(db_index=True, max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('test_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('report_url', models.URLField(blank=True, default='', max_length=2048)),
                ('gtmetrix_grade', models.CharField(blank=True, default='', max_length=4)),
                ('performance_score', models.IntegerField(blank=True, null=True)),
                ('structure_score', models.IntegerField(blank=True, null=True)),
                ('first_contentful_paint', models.FloatField(blank=True, help_text='ms', null=True)),
                ('largest_contentful_paint', models.FloatField(blank=True, help_text='ms', null=True)),
                ('cumulative_layout_shift', models.FloatField(blank=True, help_text='unitless', null=True)),
                ('total_blocking_time', models.FloatField(blank=True, help_text='ms', null=True)),
                ('time_to_interactive', models.FloatField(blank=True, help_text='ms', null=True)),
                ('speed_index', models.FloatField(blank=True, help_text='ms', null=True)),
                ('onload_time', models.FloatField(blank=True, help_text='ms', null=True)),
                ('fully_loaded_time', models.FloatField(blank=True, help_text='ms', null=True)),
                ('page_bytes', models.BigIntegerField(blank=True, null=True)),
                ('page_requests', models.IntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous submissions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gtmetrix_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GTmetrix report',
                'verbose_name_plural': 'GTmetrix reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='gtm_user_created_idx'), models.Index(fields=['status'], name='gtm_status_idx')],
            },
        ),
    ]
