# Generated by Django 5.1.7 on 2026-07-08 19:13

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(db_index=True, max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('host', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('grade', models.CharField(blank=True, default='', max_length=4)),
                ('has_warnings', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('server_name', models.CharField(blank=True, default='', max_length=255)),
                ('cert_subject', models.CharField(blank=True, default='', max_length=512)),
                ('cert_issuer', models.CharField(blank=True, default='', max_length=512)),
                ('cert_valid_from', models.DateTimeField(blank=True, null=True)),
                ('cert_valid_to', models.DateTimeField(blank=True, null=True)),
                ('cert_expires_in_days', models.IntegerField(blank=True, null=True)),
                ('cert_is_trusted', models.BooleanField(blank=True, null=True)),
                ('protocols', models.JSONField(blank=True, default=list)),
                ('vulnerabilities', models.JSONField(blank=True, default=dict)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous submissions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ssl_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSL report',
                'verbose_name_plural': 'SSL reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ssl_user_created_idx'), models.Index(fields=['host'], name='ssl_host_idx'), models.Index(fields=['status'], name='ssl_status_idx')],
            },
        ),
    ]
