# Generated by Django 5.1.7 on 2026-07-10 04:36

import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('url', models.URLField(db_index=True, max_length=2048, validators=[apps.common.validators.validate_http_url])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('crawling', 'Crawling'), ('checking_links', 'Checking links'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('total_links_found', models.IntegerField(default=0)),
                ('total_checked', models.IntegerField(default=0)),
                ('total_healthy', models.IntegerField(default=0)),
                ('total_broken', models.IntegerField(default=0)),
                ('total_redirects', models.IntegerField(default=0)),
                ('total_timeouts', models.IntegerField(default=0)),
                ('crawl_depth', models.IntegerField(default=1)),
                ('max_links', models.IntegerField(default=500)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'crawl job',
                'verbose_name_plural': 'crawl jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='crawl_status_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='LinkResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(max_length=2048)),
                ('target_url', models.URLField(db_index=True, max_length=2048)),
                ('anchor_text', models.CharField(blank=True, default='', max_length=500)),
                ('link_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], db_index=True, max_length=10)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('status_category', models.CharField(choices=[('healthy', 'Healthy'), ('broken', 'Broken'), ('redirect', 'Redirect'), ('timeout', 'Timeout'), ('error', 'Error')], db_index=True, max_length=10)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('redirect_url', models.URLField(blank=True, default='', max_length=2048)),
                ('error_detail', models.CharField(blank=True, default='', max_length=500)),
                ('crawl_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='linkchecker.crawljob')),
            ],
            options={
                'verbose_name': 'link result',
                'verbose_name_plural': 'link results',
                'ordering': ['status_category', 'target_url'],
                'indexes': [models.Index(fields=['crawl_job', 'status_category'], name='link_job_category_idx'), models.Index(fields=['crawl_job', 'link_type'], name='link_job_type_idx')],
            },
        ),
    ]
