# Generated by Django 5.1.7 on 2026-07-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkchecker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawljob',
            name='render_js',
            field=models.BooleanField(default=False, help_text='Render the page with a headless browser (for JS/SPA sites).'),
        ),
    ]
