# Generated by Django 5.1.7 on 2026-07-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkchecker', '0002_crawljob_render_js'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawljob',
            name='render_js',
            field=models.BooleanField(default=True, help_text='Render the page with a headless browser (for JS/SPA sites).'),
        ),
    ]
